#!/usr/bin/env bash

ORIG_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

command() {
  cat - <<EOF
groupmod -g $(id -g) node >/dev/null 2>&1 \
  && usermod -u $(id -u) -g $(id -g) node >/dev/null 2>&1
su node
$@
EOF
}

command "$@" | docker run --rm -i -v ${PWD}:/app -w /app node bash -
