# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Richard Testing

on:
  # via github UI
  workflow_dispatch:
  # schedule:
  #   - cron: '18 20 * * *'
  push:
    branches: [ '*' ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_webapp:
    name: Test the webapp
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Run webapp
        run: |
          docker run --rm -d --name webapp -p 8080:8080 rconway/webapp
      
      - name: Check webapp
        run: |
          curl localhost:8080
      
      - name: Stop webapp
        run: |
          docker stop webapp
      
      - name: Check webapp again
        run: |
          set +e
          curl localhost:8080
          test $? -eq 6

      # - name: Log in to registry - ${{ env.REGISTRY }}
      #   uses: docker/login-action@v2.1.0
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4.3.0
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4.0.0
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
